apiVersion: v1
kind: Pod
metadata:
  name: kaniko-tar
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args: ["--dockerfile=/workspace/dockerfile",
           "--destination=image",
           "--tarPath=/workspace/image.tar",
           "--context=dir://workspace",
           "--no-push"] 
    volumeMounts:
      - name: dockerfile-storage
        mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: kaniko-pvc
